### ISSUE TITLE
NPM plugin not updated to reflect the code

### ISSUE THREAD

**Issue by apuravchauhan** [mottox2/gatsby-plugin-workbox#1]
In gatsby-node.js, the sw build is still referring to options instead of combined options which makes it impossible for users to customize anything
~~~
var combinedOptions = _.defaults(pluginOptions, options);
return workboxBuild.generateSW(options);
~~~

**Comment by mottox2** [comment]
@apuravchauhan 
Thanks! I fixed it and released 0.1.7.
